language: node_js
node_js:
  - node
cache:
  directories:
  - node_modules
stages:
  - test
  - dev
jobs:
  include:
    - stage: test
      script:
        - npm install-test
    - stage: dev
      script:
        - npm install -g serverless
        - sls deploy -v
